/**
 * useDeepLink — reads the URL once per app boot and puts the app where the
 * link asked: `?sector=X&spot=Y` pre-selects sector + spot, and `/guia`
 * (or the older `#guia/...`) opens the guide.
 *
 * T3-5 polish (S136+3+4). When a share link generated by SpotPopup is
 * opened, the recipient lands on the correct sector with the spot popup
 * already open. URL params are stripped after use so the address bar
 * stays clean and refreshes don't re-trigger.
 */
import { useEffect } from 'react';
import { useSectorStore } from '../store/sectorStore';
import { useSpotStore } from '../store/spotStore';
import { useUIStore } from '../store/uiStore';
import { SECTORS } from '../config/sectors';
import { getSpotsForSector } from '../config/spots';
import { parseGuideTarget } from '../config/guideRoute';

export function useDeepLink(): void {
  useEffect(() => {
    if (typeof window === 'undefined') return;

    // The guide is checked FIRST and outside the early return below: a link to
    // /guia carries no sector and no spot, so anything gated on those params
    // would never see it. The modal reads the same URL to pick its section.
    const guide = parseGuideTarget(window.location.pathname, window.location.hash);
    if (guide.open) useUIStore.getState().setGuideOpen(true);

    const params = new URLSearchParams(window.location.search);
    const sectorParam = params.get('sector');
    const spotParam = params.get('spot');

    if (!sectorParam && !spotParam) return;

    if (sectorParam && SECTORS.some((s) => s.id === sectorParam)) {
      useSectorStore.getState().switchSector(sectorParam);
    }

    if (spotParam) {
      // Resolve the spot against every sector, not just the one in the URL:
      // `?spot=` may come without `?sector=` (hand-written or legacy links), or
      // with one that doesn't own it. Whoever actually has the spot wins —
      // otherwise it silently fails to open.
      const owner = SECTORS.find((s) =>
        getSpotsForSector(s.id).some((sp) => sp.id === spotParam),
      )?.id;
      if (owner) {
        if (owner !== useSectorStore.getState().activeSector.id) {
          useSectorStore.getState().switchSector(owner);
        }
        // Small delay so the sector switch fully commits before opening the
        // popup (spotStore.selectSpot needs the new sector's spots loaded).
        setTimeout(() => {
          useSpotStore.getState().selectSpot(spotParam);
        }, 250);
      }
    }

    // Strip the params so refresh doesn't re-trigger and the URL stays clean.
    const url = new URL(window.location.href);
    url.searchParams.delete('sector');
    url.searchParams.delete('spot');
    window.history.replaceState({}, '', url.toString());
  }, []); // intentional: run ONCE on mount
}
