/**
 * useDeepLink — reads `?sector=X&spot=Y` from the URL on mount and
 * pre-selects the matching sector + spot. Runs ONCE per app boot.
 *
 * T3-5 polish (S136+3+4). When a share link generated by SpotPopup is
 * opened, the recipient lands on the correct sector with the spot popup
 * already open. URL params are stripped after use so the address bar
 * stays clean and refreshes don't re-trigger.
 */
import { useEffect } from 'react';
import { useSectorStore } from '../store/sectorStore';
import { useSpotStore } from '../store/spotStore';
import { SECTORS } from '../config/sectors';
import { getSpotsForSector } from '../config/spots';

export function useDeepLink(): void {
  useEffect(() => {
    if (typeof window === 'undefined') return;
    const params = new URLSearchParams(window.location.search);
    const sectorParam = params.get('sector');
    const spotParam = params.get('spot');

    if (!sectorParam && !spotParam) return;

    let sectorId: string | null = null;
    if (sectorParam && SECTORS.find((s) => s.id === sectorParam)) {
      sectorId = sectorParam;
      useSectorStore.getState().switchSector(sectorParam);
    }

    if (spotParam) {
      // Find the spot in the (possibly newly-switched) sector. If sectorParam
      // wasn't provided, search all spots; fall back to current sector.
      const targetSector = sectorId ?? useSectorStore.getState().activeSector.id;
      const spots = getSpotsForSector(targetSector);
      const match = spots.find((s) => s.id === spotParam);
      if (match) {
        // Small delay so the sector switch fully commits before opening the
        // popup (spotStore.selectSpot needs the new sector's spots loaded).
        setTimeout(() => {
          useSpotStore.getState().selectSpot(spotParam);
        }, 250);
      }
    }

    // Strip the params so refresh doesn't re-trigger and the URL stays clean.
    const url = new URL(window.location.href);
    url.searchParams.delete('sector');
    url.searchParams.delete('spot');
    window.history.replaceState({}, '', url.toString());
  }, []); // intentional: run ONCE on mount
}
